### ISSUE TITLE
Force password change at next login

### ISSUE THREAD

**Issue by Zillion01** [codesource/typo3-cdsrc_bepwreset#27]
Installed latest extension, update db, cleared cache, set checkbox at backend user "Force password change at next login"

User still can login and gets no message.
TYPO3 10.4.21

**Comment by codesource** [comment]
I will check that.

**Comment by anaristickw** [comment]
In ext_localconf.php file, overwrite line 6 with code:
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_userauth.php']['postUserLookUp'][] = 'CDSRC\CdsrcBepwreset\Hooks\UserAuthHook->postUserLookUp';`

In UserAuthHook.php file, instead of importing `TYPO3\CMS\Lang\LanguageService;` import:
`use TYPO3\CMS\Core\Localization\LanguageService;`

After this "Force password change at next login" should work.

**Comment by codesource** [comment]
Thanks to @anaristickw to have point the changes.
